name: Compilar y Probar

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configurar CMake
      run: cmake -B build -S .

    - name: Compilar
      run: cmake --build build

    - name: Ejecutar pruebas
      # Corre los tests y muestra la salida en caso de error
      run: cd build && ctest --output-on-failure
